

const Employee1 = {
    FullName: "Ghazi Samer",
    Department: "Administration",
Level : "Senior",
Salary : function () {
    ID = (Math.random() * (2000 - 1500) + 1500) ;
    Net = ID - (ID * 0.075) 
        console.log(Net)
    },
    Employee_ID : function ( ) {
        console.log(ID = Math.floor(1000 + Math.random() * 9000))
    }
    
  };
  
  const Employee2 = {
    FullName: "Lana Ali	",
    Department: "Finance",
Level : "Senior",  
Salary : function () {
    ID = (Math.random() * (2000 - 1500) + 1500) ;
    Net = ID - (ID * 0.075) 
        console.log(Net)
    },
  Employee_ID : function ( ) {
    console.log(ID = Math.floor(1000 + Math.random() * 9000))

  }};
  const Employee3 = {
    FullName: "Tamara Ayoub",
    Department: "Marketing",
Level : "Senior",
Salary : function () {
    ID = (Math.random() * (2000 - 1500) + 1500) ;
    Net = ID - (ID * 0.075) 
        console.log(Net)
    },
    Employee_ID : function ( ) {
        console.log(ID = Math.floor(1000 + Math.random() * 9000))
    }  };
  const Employee4 = {
    FullName: "Safi Walid",
    Department: "Administration",
Level : "Mid-Senior",
Salary : function () {
    ID = (Math.random() * (1500 - 1000) + 1000) ;
Net = ID - (ID * 0.075) 
    console.log(Net)
},
    Employee_ID : function ( ) {
        console.log(ID = Math.floor(1000 + Math.random() * 9000)) }
  };
  const Employee5 = {
    FullName: "Omar Zaid",
    Department: "Development",
Level : "Senior",
Salary : function () {
ID = (Math.random() * (2000 - 1500) + 1500) ;
Net = ID - (ID * 0.075) 
    console.log(Net)
},
    Employee_ID : function ( ) {
        console.log(ID = Math.floor(1000 + Math.random() * 9000))}
  };
  const Employee6 = {
    FullName: "Rana Saleh",
    Department: "Development",
Level : "Junior",
Salary : function(){ID = (Math.random() * (1000 - 500) + 500) ;
Net = ID - (ID * 0.075) 
    console.log(Net)
},
    Employee_ID : function ( ) {
        console.log(ID = Math.floor(1000 + Math.random() * 9000))}
  };
  const Employee7 = {
    FullName: "Hadi Ahmad",
    Department: "Finance",
Level : "Mid-Senior",
Salary : function () {
    ID = (Math.random() * (1500 - 1000) + 1000) ;
Net = ID - (ID * 0.075) 
    console.log(Net)
},
    Employee_ID : function ( ) {
        console.log(ID = Math.floor(1000 + Math.random() * 9000))}
  };
  console.log("Full Name : " + Employee1.FullName)
  Employee1.Salary()
  console.log("Full Name " + Employee2.FullName)
  Employee2.Salary()
  console.log("Full Name "+Employee3.FullName)
  Employee3.Salary()
  console.log( " Full Name : " +Employee4.FullName)
  Employee4.Salary()
  console.log( " Full Name : " + Employee5.FullName)
  Employee5.Salary()
  console.log( " Full Name : " + Employee6.FullName)
  Employee6.Salary()
  console.log( " Full Name : " + Employee7.FullName)
  Employee7.Salary()

